services:
  server:
    environment:
      - NODE_ENV=development
      - DEBUG=*
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:3001:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
