services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:5173:5173"
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
        - action: sync
          path: ./client/public
          target: /app/public
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/yarn.lock
