services:
  server:
    build:
      context: ./server
      target: production
    environment:
      - NODE_ENV=production
    volumes: []
    command: ["node", "dist/main"]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:80:80"
    environment:
      - NODE_ENV=production
